/**
 * Represents a user profile within the OrderEazy system.
 */
export interface User {
  /** The unique username of the user. */
  username: string;
  /** The name of the organization the user belongs to. */
  organization: string;
  /** Whether the user has administrative privileges. */
  is_admin: boolean;
  /** The email address of the user (optional). */
  email?: string;
  /** A URL pointing to the user's or organization's logo image (optional). */
  logo_url?: string;
}

/**
 * Represents a sales order in the system.
 */
export interface Order {
  /** Unique identifier for the order. */
  order_id: number;
  /** The organization that placed or owns the order. */
  org: string;
  /** Name of the person or entity receiving the order. */
  receiver_name: string;
  /** The date the order was placed (Format: YYYY-MM-DD). */
  date: string;
  /** The expected date for order fulfillment (Format: YYYY-MM-DD). */
  expected_delivery_date: string;
  /** The name or ID of the product ordered. */
  product: string;
  /** Additional details or notes about the order (optional). */
  description?: string;
  /** Total units of the product ordered. */
  quantity: number;
  /** Selling price per unit. */
  price: number;
  /** Base price before taxes or markings. */
  basic_price: number;
  /** GST amount applied to the order. */
  gst: number;
  /** Amount paid by the customer in advance. */
  advance_payment: number;
  /** The final total amount including GST. */
  total_amount_with_gst: number;
  /** The remaining balance to be paid. */
  pending_amount: number;
  /** Current fulfillment status. */
  status: "Completed" | "Pending";
  /** Total units successfully delivered so far. */
  delivered_quantity: number;
  /** URL to any associated electronic document or invoice (optional). */
  url?: string;
  /** The username of the person who created this order (optional). */
  created_by?: string;
  /** Dynamic key-value pairs for business-specific data (optional). */
  custom_data?: Record<string, string>;
}

/**
 * Represents a specific delivery associated with an order.
 */
export interface Delivery {
  /** The ID of the parent order. */
  order_id: number;
  /** Unique identifier for this specific delivery shipment. */
  delivery_id: number;
  /** The organization handling the delivery. */
  org: string;
  /** Quantity of units delivered in this specific shipment. */
  delivery_quantity: number;
  /** The date the delivery was made (Format: YYYY-MM-DD). */
  delivery_date: string;
  /** Total payment received during this delivery. */
  total_amount_received: number;
  /** Cloudinary or external asset unique identifier (optional). */
  public_id?: string;
  /** URL to the delivery slip or proof of delivery (optional). */
  url?: string;
  /** Original filename of the uploaded document (optional). */
  file_name?: string;
  /** Timestamp when the delivery record/file was uploaded (optional). */
  upload_date?: string;
  /** Type of resource uploaded (e.g., 'image', 'pdf') (optional). */
  resource_type?: string;
  /** Dynamic metadata for the delivery (optional). */
  custom_data?: Record<string, string>;
}

/**
 * High-level summary of business performance shown on the dashboard.
 */
export interface DashboardSummary {
  /** Cumulative count of all orders. */
  total_orders: number;
  /** Count of orders with 'Completed' status. */
  completed_orders: number;
  /** Count of orders still in 'Pending' status. */
  pending_orders: number;
  /** Total volume of units shipped across all orders. */
  total_units_delivered: number;
}

/**
 * Performance metrics filtered for the current calendar month.
 */
export interface CurrentMonthMetrics {
  total_orders: number;
  completed_orders: number;
  pending_orders: number;
  units_delivered: number;
}

/**
 * Structured data used for multi-dimensional revenue visualization.
 */
export interface BubbleChartData {
  /** The grouping name (e.g., product name or category). */
  name: string;
  /** Total units associated with this group. */
  quantity: number;
  /** Total revenue generated by this group. */
  revenue: number;
  /** Number of unique orders in this group. */
  orders: number;
}

/**
 * Detailed record for the "Recent Activity" feed.
 */
export interface RecentActivityData {
  id: string;
  product: string;
  receiver: string;
  amount: number;
  quantity: number;
  delivered_quantity: number;
  pending_amount: number;
  status: string;
  payment_status: string;
  date: string;
}

/**
 * Data representing the time difference between expected and actual delivery dates.
 */
export interface FulfillmentGapData {
  order_id: number;
  product: string;
  /** Expected delivery timestamp. */
  expected: string;
  /** Actual delivery timestamp. */
  actual: string;
  /** Number of days between expected and actual (can be negative for delays). */
  days_gap: number;
}

/**
 * Response structure for AI-driven revenue forecasting.
 */
export interface ForecastResponse {
  /** The statistical R-squared score of the model. */
  r2_score: number;
  /** Qualitative confidence string (e.g., "High", "Medium"). */
  confidence_level: string;
  /** Historical monthly revenue data used for the baseline. */
  historical_data: {
    month: string;
    revenue: number;
  }[];
  /** Predicted revenue for the next 12 months with bounds. */
  forecast_12_months: {
    month: string;
    predicted_revenue: number;
    lower_bound: number;
    upper_bound: number;
  }[];
}

/**
 * Metadata for Recency, Frequency, Monetary (RFM) customer segmentation.
 */
export interface RFMSegmentData {
  /** List of customer names belonging to this segment. */
  customers: string[];
  /** Total count of customers in this segment. */
  count: number;
  /** Plain English explanation of what this segment represents (e.g., "At Risk"). */
  business_explanation: string;
}

/**
 * Complete RFM analysis response.
 */
export interface RFMResponse {
  /** Map of segment names to their detailed data. */
  segments: Record<string, RFMSegmentData>;
  /** Raw RFM calculation table. */
  rfm_table: any[];
}

/**
 * summary information for system administrators.
 */
export interface OrganizationSummary {
  organization: string;
  orders_count: number;
  deliveries_count: number;
}

/**
 * Financial revenue aggregated by year.
 */
export interface YearlyRevenue {
  [year: string]: number;
}

/**
 * Month-over-Month growth percentages.
 */
export interface MoMGrowth {
  [month: string]: number;
}

/**
 * Total pending revenue aggregated by month.
 */
export interface PendingMonthly {
  [month: string]: number;
}

/**
 * Aggregated data for highest performing customers.
 */
export interface TopCustomers {
  /** All-time top customers by revenue. */
  top_total: { [name: string]: number };
  /** Top customers broken down by year. */
  top_yearly: { [year: string]: { [name: string]: number } }[];
  /** Top customers broken down by month. */
  top_monthly: { [month: string]: { [name: string]: number } }[];
}

/**
 * Performance statistics for a single product.
 */
export interface ProductStat {
  name: string;
  quantity: number;
  revenue: number;
  order_count: number;
}

/**
 * List of product statistics for analytics views.
 */
export interface ProductAnalyticsResponse {
  products: ProductStat[];
}

/**
 * Customer retention and churn data over time.
 */
export interface ChurnData {
  month: string;
  /** Count of new customers added this month. */
  new: number;
  /** Count of returning customers who transacted this month. */
  returning: number;
}

/**
 * Average Order Value (AOV) metrics.
 */
export interface AOVData {
  month: string;
  /** The average order value for this month. */
  aov: number;
  /** Total monthly revenue. */
  revenue: number;
  /** Total monthly orders count. */
  orders: number;
}

/**
 * Visualization data for delivery efficiency.
 */
export interface DeliveryFragmentationData {
  name: string;
  value: number;
  [key: string]: any;
}

/**
 * Metric tracking revenue tied up in undelivered units.
 */
export interface RevenueHostageData {
  month: string;
  unpaid_units: number;
  held_revenue: number;
}

/**
 * High-level summary of delivery operations.
 */
export interface DeliveryPerformanceMetrics {
  total_orders: number;
  total_deliveries: number;
  total_quantity: number;
  total_amount: number;
}

/**
 * Distribution of deliveries within specific ranges (e.g., "0-5 days").
 */
export interface DeliveryDistribution {
  range: string;
  count: number;
}

/**
 * Raw data for revenue vs quantity scatter plots.
 */
export interface ScatterData {
  order_id: number;
  quantity: number;
  revenue: number;
  product: string;
}

/**
 * Activity frequency data for heatmap visualizations.
 */
export interface HeatmapData {
  date: string;
  count: number;
}

/**
 * Projected delivery quantities for the upcoming schedule.
 */
export interface ExpectedScheduleData {
  date: string;
  total_quantity: number;
}
